// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace AutopartesApi.Entities;

public partial class Autoparte
{
    
    public int IdAutoparte { get; set; }

    public string MotivoBaja { get; set; }

    public DateOnly? FechaBaja { get; set; }

    public string Estado { get; set; }

    public int? Stock { get; set; }

    public decimal? Precio { get; set; }

    public string Descripcion { get; set; }

    public int? IdCategoria { get; set; }
    [JsonIgnore]
    public virtual ICollection<DetallesFactura> DetallesFacturas { get; set; } = new List<DetallesFactura>();
    [JsonIgnore]
    public virtual Categoria IdCategoriaNavigation { get; set; }
}