// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace AutopartesApi.Entities;

public partial class DetallesFactura
{
    
    public int IdDetalle { get; set; }

    public int? IdFactura { get; set; }

    public int? IdAutoparte { get; set; }

    public string Cantidad { get; set; }

    public decimal? PrecioU { get; set; }
    [JsonIgnore]
    public virtual Autoparte IdAutoparteNavigation { get; set; }
    [JsonIgnore]
    public virtual Factura IdFacturaNavigation { get; set; }
}