// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace AutopartesApi.Entities;

public partial class Empleado
{
    
    public int IdEmpleado { get; set; }

    public string Contraseña { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Mail { get; set; }

    public int? IdCargo { get; set; }
    [JsonIgnore]
    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();
    [JsonIgnore]
    public virtual Cargo IdCargoNavigation { get; set; }
}